[package]
name = "stud-rust-base"
version = "0.1.0"
authors = ["Tim Zeitz <tim.zeitz@kit.edu>"]
edition = '2018'

[dependencies]
time = "^0.1.40"
rand = "0.8.4"
num = "0.4.0"

#[dependencies.rust_road_router]
#path = "../rust_road_router/engine"